### ISSUE TITLE
图片上传存在跨域问题

### ISSUE THREAD

**Issue by yexiaodong** [ff755/vue-kindedtior-demo#11]
kindeditor-all-min.js:2 Uncaught DOMException: Blocked a frame with origin "http://localhost:8384" from accessing a cross-origin frame.
    at Function._iframeDoc [as iframeDoc] (http://localhost:8384/js/chunk-vendors.5874590b.js:1:35596)
    at HTMLIFrameElement.<anonymous> (http://localhost:8384/js/chunk-vendors.5874590b.js:1:89564)
    at Function.<anonymous> (http://localhost:8384/js/chunk-vendors.5874590b.js:1:15942)
    at _each (http://localhost:8384/js/chunk-vendors.5874590b.js:1:12622)
    at HTMLIFrameElement.r.length.r.(anonymous function) (http://localhost:8384/js/chunk-vendors.5874590b.js:1:15910)

**Comment by iiwawe** [comment]
@yexiaodong 你的问题解决了吗，我遇到了同样的问题。

**Comment by ff755** [comment]
跨域访问的问题 配置服务端

**Comment by qiugu** [comment]
大佬，这个是iframe的跨域，服务端怎么配置啊

**Comment by ff755** [comment]
后端用什么写的

**Comment by qiugu** [comment]
后端是java springboot写的

**Comment by qiugu** [comment]
大佬，急需帮助哇

**Comment by ff755** [comment]
在后端程序配置

**Comment by ff755** [comment]
稍等 我这好像有写过的 帮你查下

**Comment by ff755** [comment]
`@Configuration
public class WebMvcConfig implements WebMvcConfigurer {


    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
       
    }

    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**");
    }


}
`

**Comment by ff755** [comment]
写个配置文件就可以  
`@Override
public void addCorsMappings(CorsRegistry registry) {
    registry.addMapping("/**");
}`
